[versions]
agp = "8.7.3"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.6.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
usbserial = "3.7.3"
usbSerialForAndroid = "3.11.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
usb-serial-for1-android-v3110 = { module = "com.github.mik3y:usb-serial-for-android", version.ref = "usbSerialForAndroid" }
usbserial = { group = "com.github.mik3y", name = "usb-serial-for-android", version.ref = "usbserial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
